# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_remove_drink_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.DrinkCategory'),
        ),
    ]
