# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0003_drink_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ice', models.PositiveSmallIntegerField(choices=[(0, 'No Ice'), (10, '50% Ice'), (20, '100% Ice')], default=20, verbose_name='status')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Manager.Drink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
