# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0004_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
